<?php
/*
     ------------------------------------------------------------------------------------
    Copyright (C) 2002, 2003 Jerome Chevillat
    Contact: jerome@chevillat.ch, contact@smoothplanet.com
     ------------------------------------------------------------------------------------

    This file is part of picsPHP.

    picsPHP is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    picsPHP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with picsPHP; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
    
*/
?>
<?php

$album=$_GET['album'];
$nbpage=$_GET['nbpage'];
$picture=$_GET['picture'];
$browse=$_GET['browse'];
$lang=$_GET['lang'];

global $album_php_config;

# $album check for security reason;
if (empty($album)) {
     $album="";
} else {
     if (!ereg('^[^..]*$', $album)) {
          die('bad album name');
     }
     if ($album{strlen($album)-1}=="/") {
          $album=substr($album, 0, strlen($album)-1);
     }
}

# $browse check for security reason;
if (empty($browse)) {
     $browse=".";
} else {
     if (!ereg('^[^..]*$', $browse)) {
          die('bad directory name');
     }
     if ($browse{strlen($browse)-1}!="/") {
          $browse="$browse/";
     }
}

# validation of $nbpage variable
if (empty($nbpage)) {
   $nbpage=1;
}
if ($nbpage<1) {
     $nbpage=1;
}

# validation of $lang variable
if (empty($lang)) {
     $lang=$default_lang;
}

function getFileList( $dirname="." ) {
     global $thumb_prefix;
     $files = array(); 
     $dir = opendir( $dirname );
     while($file = readdir($dir)) {
          if (ereg("jpg$",$file) || ereg("JPG$",$file) || ereg("jpeg$",$file) || ereg("JPEG$",$file) || ereg("gif$",$file) || ereg("GIF$",$file)) {
               if (!is_integer(strpos($file, $thumb_prefix))) {
                    $files[] = $file; 
               }
          }
     }
     sort($files);
     closedir($dir);
     return $files; 
} 

# ****************************************************************************************
# Common functions called from all pages
# ****************************************************************************************

function getStylesheet() {
     global $album_stylesheets;
     foreach ($album_stylesheets as $cur_css) {
          if (file_exists("inc/css/$cur_css")) {
               echo "<link href=\"inc/css/$cur_css\" rel=\"stylesheet\" type=\"text/css\" />\n";
          }
     }
}

function getWindowTitle() {
     global $my_album, $album, $picture, $files;
     echo "<title>$my_album";
     if ($album!="") {
          echo " ::: ";
          echo getAlbumTitleText();
     }
     if ($picture!="") {
          echo " ::: ";
          echo getPictureTitleText();
     }
     echo "</title>";
}

function getThanksTo() {
     echo "<div id=\"thanksTo\">Album Generated by <a href=\"http://www.smoothplanet.com/sp/soft/picsPHP\" target=\"new_window\">picsPHP</a></div>";
}

# ****************************************************************************************
# Common functions to all three programs
# ****************************************************************************************

function getAlbumTitleText($path="") {
     global $album, $my_album, $lang;
     if ($path=="") {
          $path="$album/";
     }
     $albumfile = "album.txt";
     if (file_exists("${path}album_$lang.txt")) {
          $albumfile = "album_$lang.txt";
     }
     if (file_exists("${path}$albumfile")) {
          $album_file = file("${path}$albumfile", "r");
          $text = $album_file[0];
          return $text;
     } else {
          if ($path==".") {
               return "$my_album";
          } else {
               $path_parts = pathinfo("$path");
               return $path_parts["basename"];
          }
     }
}

function getAlbumDescriptionText($path="") {
     global $album, $lang;
     $text="";
     if ($path=="") {
          $path="$album/";
     }
     $albumfile = "album.txt";
     if (file_exists("${path}album_$lang.txt")) {
          $albumfile = "album_$lang.txt";
     }
     if (file_exists("${path}$albumfile")) {
          $album_file = file("${path}$albumfile", "r");
          $current = 1;
          while ($current <= sizeof($album_file)) {
               $text .= "$album_file[$current]\n";
               $current++;
          }
     }
     return $text;
}

function getPictureTitleText() {
     global $album, $files, $picture, $lang;
     $picturename = getFilename($files[$picture]);
     $picturefile = "$picturename.txt";
     if (file_exists("${album}/$picturename_$lang.txt")) {
          $picturefile = "$picturename_$lang.txt";
     }
     if (file_exists("${album}/$picturefile")) {
          $picture_file = file("${album}/$picturefile", "r");
          return "$picture_file[0]";
     }
     else {
          return "$picturename";
     }
}

function getPictureTitleDescriptionText() {
     global $album, $files, $picture, $lang;
     $text="";
     $picturename = getFilename($files[$picture]);
     $picturefile = "$picturename.txt";
     if (file_exists("${album}/$picturename_$lang.txt")) {
          $picturefile = "$picturename_$lang.txt";
     }
     if (file_exists("${album}/$picturefile")) {
          $picture_file = file("${album}/$picturefile", "r");
          $current = 1;
          while ($current <= sizeof($picture_file)) {
               $text .= "$picture_file[$current]\n";
               $current++;
          }
     }
     return $text;
}

# ****************************************************************************************
# 'Private' functions
# ****************************************************************************************

function getFilename($filewithextension) {
     $arr = split("\.",$filewithextension);
     return $arr[0];
}

function isValidPictureDirectory($dir) {
     global $not_browsable_folder;
     return !(in_array ($dir, $not_browsable_folder));
}

function isValidPictureFile($file) {
     return (ereg("jpg$",$file) || ereg("JPG$",$file) || ereg("jpeg$",$file) || ereg("JPEG$",$file) || ereg("gif$",$file) || ereg("GIF$",$file));
}

function getPictureSize($toPicture) {
     global $album;
     $size = getimagesize ("$album/$toPicture");
     return "width=\"$size[0]\" height=\"$size[1]\"";
}

function getThumbnailSize($toPicture) {
     global $album, $thumb, $thumb_resize;
     $thumbPath = getThumbnailPath($toPicture);
     if (!file_exists("$thumbPath")) {
          return "";
     }
     $size = getimagesize ("$thumbPath");
     if ($thumb) {
          return "width=\"$size[0]\" height=\"$size[1]\"";
     } else {
          return "width=\"".round($size[0]*$thumb_resize/100)."\" height=\"".round($size[1]*$thumb_resize/100)."\"";
     }
}

function getThumbnailPath($toPicture) {
     global $album, $thumb, $thumb_dir, $thumb_prefix;
     if ($thumb) {
           return "$album/$thumb_dir/$thumb_prefix$toPicture";
     } else {
          return "$album/$toPicture";
     }
}

?>