<?php
require("/home/emahe/Desktop/tdm/web/header.html");
?> 

<div class="main-inside">

<br/>

<div class="titre">
Uyuni
</div>
<p>
<div class="resume">
El buen mochilero
</div>
<p>
<a id="texte"></a>
<div class="texte">

<h2>4 fevrier</h2>
Immediatement a l'arrivee, je suis pris en charge par les agences de tourisme locales. Je vais finir ma nuit a l'Hotel Marith, gratuit si je prends le tour du Salar avec l'agence. Le ciel est pur, ici, on voit beaucoup d'etoiles. Je regarde le lever du soleil de la cour de l'hotel, c'est magique.
<h2>5 fevrier</h2>
Le 4x4 passe me prendre devant l'hotel. Je suis le dernier a monter a bord. Il y a deja Olivier (Fr), Damien (Es, Majorque) et ? (Es, Barcelone). Premier arret: un petit village ou le sel est traite, c'est-a-dire qu'ils en font du sel fin. C'est la seule machine que je vois ici. Il y a bien une usine dans le village, mais elle a l'air arretee. Toute construction metallique et mecanique a une duree de vie assez limitee dans la region, semble-t-il. Ils fabriquent aussi quelques sculptures de sel pour les touristes. Nous ne sommes pas les premiers a nous arreter, il y a deja plusieurs 4x4 des autres agences, et il en arrve encore. Nous nous arretons ensuite peu apres avoir penetre dans le Salar proprement dit. Des travailleurs avec des pelles et des pioches font des petits tas de sel ou chargent les tas dans des camions. Tout a la main. En fait, le tourisme leur rapporte plus que l'extraction du sel, donc ils extraient le sel plus lentement, pour que le Salar dure plus longtemps. Mentalite Bolivienne, vous ne pouvez pas comprendre. Je peux voir quelques flaques ici et la, mais le Salar est sec, tout blanc. C'est rate pour les "reflets hallucinants" du L.P. Nous embarquons de nouveau pour ce qui ressemble a un poste avance sur l'Antarctique. Un drapeau surmontant un tas de sel, une construction abandonnee de chaque cote, et derriere le Salar a perte de vue. Le soleil est deja haut, le Salar brille intensement. En fait, nous sommes devant un hotel abandonne, construit en sel. Briques de sel pour les murs, et mobilier interieur en sel egalement. L'hotel coutait trop cher en entretien, allez construire des canalisations d'eau dans un environnement ultra-sale.<p>
Nous faisons ensuite un bout de route, direction Isla del Pescado. C'est un rocher couvert de cactus qui donne l'impression d'une ile deserte au milieu de l'ocean. Blanc. Ca me fait un choc a chaque fois qu'un 4x4 passe sur l'eau, non le sel. Nous pique-niquons sur place. Arret final sur le Salar: des sources d'eau crevent la croute de sel, ca produit une mare d'au moins deux metres. Bon. Nous finissons le tour par la visite de la vieille gare de marchandises. Il y avait une mine a Uyuni dans le temps. Aujourd'hui, il ne reste que les locomotives, style western annees 20, a l'abandon. Notre guide arrete le 4x4: "Vieja estacion, 30 mn". Peu loquace, le guide. Par chance le guide du 4x4 suivant nous donne quelques details. C'etait une gare importante a l'epoque, les locos sont de fabrication Tchequoslovaque. La mine s'est arretee a cause d'une mauvaise gestion. Aujourd'hui c'est un joli tas de ferraille recouvert de rouille, et de mouches. Nous reprenons la route a 4000 vers le centre d'Uyuni. Nous nous arretons en route pour virer les 3995 mouches que nous avons pris en stop. Et la ballade est finie.<p>
Nous trouvons un bar en deux secondes a peine, le sel ca donne soif. Quelques bieres plus tard, nous avons designe Olivier pour faire le service, car c'est le seul a savoir eviter la mousse. Facile, il tient un bar en France. Ici comme partout en altitude, la mousse est l'ennemi numero 1 du buveur de biere.<p>
Je ne sais toujours pas comment je vais sortir de ce trou a rat, train ou bus ? J'y vais apres la prochaine binouze. Il se met a pleuvoir, nous nous refugions a l'interieur. La musique est bonne: Pink Floyd, Stones, Deep Purple (Je sais ce que vous allez dire: c'est de la musique pour touristes. Il vaudrait mieux ecouter le folklore local. Le probleme ici, c'est que tout le monde ecoute le folklore local. Si dans 90% des bars parisiens on ecoutait du Piaf, vous aussi vous iriez ecouter les Stones en cachette). De fil en aiguille, on en vient a commander des pizzas. Olivier va se coucher, demain il prend un bus pour Potosi. J'accompagne les Espagnols a la gare. Ils vont prendre le train pour Oruro. Le train des Espagnols est a 23h, et moi je vais prendre le train en sens inverse, vers la frontiere argentine. J'espere que vous avez une carte de la region sous les yeux parce que je n'ai pas l'intention de vous expliquer la geographie Bolivienne, surtout avec ce qui est sur le point de m'arriver. La gare ouvre a 22h, donc le guichet ouvre effectivement 22h45. C'est un retard de bon aloi. Le tableau d'affichage (a la craie sur tableau noir, ne revez pas!) indique deux trains, un le mercredi (on est mercredi) et un le diamnche. Mon train arrive a 2h du matin, soit 3 heures d'attente de plus que les Espagnols. Attends, c'est quoi, le "+1" en tous petits caracteres a cote de l'horaire ? Ca veut dire "jour suivant", c'est-a-dire jeudi, 2 heures du matin. Ah bon. OK, changement de plan, je vais a Oruro avec les autres, je ne veux pas rester coince ici, c'est la zone. Au moins si je veux glander a Oruro il y aura quelque chose a faire. Je passerai par Potosi au retour, ou dans le pire des cas je prendrai le meme train en sens inverse, depuis Oruro. 38 Bolivianos, ce n'est pas la mort. Les deux Espagnols ont deja leur billet, j'achete le mien, le guichetier me previent: ca sera "sin horario". C'est-a-dire sans horaire. Je ne suis pas d'un naturel inquiet, mais ca fait quand meme bizarre. En fait, le train est bloque par une greve de mineurs entre Uyuni et la frontiere, dans une petite ville appelee Atocha.<p>
Commence une longue nuit d'attente dans la cafeteria de la gare. Nous regardons la television, nous parlons de temps en temps et nous finissons par nous resigner. A 2AM, Damien invente le jeu "El buen mochillero". Ils sont eploses de rire, c'est les nerfs. Je demande a Damien de me les ecrire comme ca je pourrai rire aussi, il n'y a pas de raison. Ce sont des phrases du type: "En Union Sovietique, on ne conduit pas les voitures, ce sont elles qui vous conduisent"<p>
Par exemple, "Un bon backpacker (Un buen mochillero) ne fait pas le tour du monde, c'est le monde qui lui tourne autour"<p>
"Un bon backpacker ne voyage pas, il souffre", etc...<p>
A 3AM, il vont dormir (par terre, dans la cafeteria), et un tcheque d'une table voisine, imbibe de biere, vient prendre le relais. Un peu plus tard, je vais dormir a mon tour. Damien me reveille a 7AM. Le train est toujours bloque, je me fais rembourser le billet sans probleme. Une voyageuse Bolivienne vient nous annoncer qu'un bus de 40 places est pret a partir pour Oruro. Les Espagnols sont interesses, moi je vais voir le terminal de bus a 15 minutes a pied de la. Le bus pour la ville-frontiere de Villazon est parti a 7AM, bon. Mais il y a un "camione" qui part demain a la meme heure a Tupiza, derniere etape avant Villazon. Retour a la gare, le bus pour Oruro n'est toujours pas parti, il manque 15 personnes. Les passagers doivent se cotiser pour payer la difference.Je prends une chambre a proximite de la gare, au cas ou le blocus serait leve, et je me premene dans cette petite ville aux larges avenues pavees, mais aux toutes petites maisons pourries. Mauvaise redistribution de l'argent du tourisme par le gouvernement local, apparemment. Comme partout en Bolivie, il y a un marche bien achalande, de bons jus de fruits, des patisseries artisanales. Qui m'a dit que j'allais maigrir pendant mon voyage ? J'achete le journal pour me cultiver un peu, rien sur Atocha. Je trouve au marche de quoi manger pour le soir: du pain, une 1/2 bouteille de vin chilien et du fromage de chevre qui me fait envie depuis La Paz.<p>
<h2>6 fevrier</h2>
Le "camione" (aka 4x4, pas facile a prononcer hein?) ne va que jusqu'a Atocha a cause du bloqueo. Va pour Atocha, je suis pret a tout. Nous embarquons a 11 dans ce qui a du etre un Land Cruiser il y a tres longtemps. Il y a 3 personnes sur la banquette avant, 4 plus un petit garcon sur la banquette arriere, et 5 dans le coffre, assis perpendiculairement au sens de la marche. La route (non, la piste) est pourrie, il me semble qu'on derape sur les graviers a peu pres tous les 15 metres. Nous arrivons au but, une montagne de chaque cote, quand le 4x4 s'arrete: bloqueo. Nous finissons a pied sur 20 minutes le long de la voie ferree. De nombreux groupes marchent en sens inverse pour attraper un bus ou un 4x4 qui rebrousse chemin vers Uyuni. Surprise, il y a un autre bloqueo au sud de la ville. Nous sommes coinces la, comme tous les habitants d'Atocha. Apres enquete sur place, elimination des temoignages fantaisistes et moyennage, nous en arrivons a la conclusion suivante: les mineurs font greve (bien), et ils negocient a La Paz en ce moment avec le gouvernement pour debloquer la situation. Debut des negos a 11AM, fin vers 1PM. Le train est effectivement a Atocha, mais il partira vers Oruro des la fin de la greve. Mauvaise pioche. Notre seul espoir sont les bus stationnes sur la place du village, ils sont deja aux 3/4 pleins, prets a bondir vers Tupiza au moindre fremissement des mineurs. Ils sont optimistes.<p>
Nous (Tom l'Irlandais, les 4 Argentins Juan, Virginia, Mariano et sa copine, et moi) formons un tas avec nos sacs et nous preparons a une longue attente pres des bus. Nous en profitons pour gouter les empanadas, pasteques, bananes, mangues et raisins d'Atocha. Vers 6PM, les bus (qui se sont vides, pus re-remplis, puis re-vides au fil des rumeurs sur le train des negociations) remettent les moteurs en route, et nous emmenent a un rythme funeraire en direction du blocus sud. Les mineurs sont une petite centaine, la plupart allonges ou discutant sur le bord de la route mais un groupe d'environ 20 mineurs garde la route. Nous attendons la pendant une heure, puis les mineurs lancent quelques explosifs pour nous signifier la fin de la greve. Nous sommes passes. Nous arrivons a Tupiza vers 11PM. Le prochain bus pour Villazon part a 2AM, pas question de payer une nuit pour moins de 3 heures. Nous nous retrouvons dans le seul endroit encore ouvert a cette heure: le bar-boite-karaoke. Les Argentins prennent la chose assez bien, Tom et moi sommes morts de rire: le karaoke est a peu pres aussi bien vu en Irlande qu'en France. Nous arrivons cependant a accompagner les locaux sur les chansons a l'eau de rose, car ca ne va pas trop vite. Les Argentins sont morts de rire. Ils demandent un tango. Je savais que le tango est difficile a danser mais c'est encore plus dur a chanter! Les sous-titres defilent a toute vitesse, le seul a tenir la mesure est Mariano.<p>
<h2>7 fevrier</h2>
Tout le monde dort pendant le trajet jusqu'a Villazon. Traversee a pied, puis douanes. Nous nous separons cote Argentin (La Quiaca): Les Argentins rentrent a Buenos Aires, c'est la fin des vacances. Tom et moi prenons le bus pour Salta. Tom me dit que le paysage etait magnifique, je n'en sais rien car j'ai dormi la bouche ouverte pendant tout le voyage.



</div>


<p>
<a href="#top">Revenir en haut</a>
</p>

 </div>
<?php
require("/home/emahe/Desktop/tdm/web/footer.html");
?> 
