<?php
require("/home/emahe/Desktop/tdm/web/header.html");
?> 

<div class="main-inside">

<br/>

<div class="titre">
Cuzco
</div>
<p>
<div class="resume">
Le Huayna Picchu
</div>
<p>
<a id="texte"></a>
<div class="texte">

<h2>21 janvier</h2>
Nous sommes a Cuzco a 6h du matin. Je file a l'hotel "Royal Cuzco" (L.P. pres de la Plaza de Armas) ou je finis ma nuit.<p>
Petit conseil: si vous donnez rendez-vous a quelqu'un dans n'importe quelle ville du Perou, choisissez la Plaza de Armas, vous etes sur de ne pas vous tromper.<p>
En debut d'apres-midi, je prends l'escalier direction les ruines de Saqsahuaman, la pente est raide mais je grimpe. 
Arrive en haut, je croise une Francaise d'origine iranienne, Karine alias Golnouche(?), qui est en train de negocier une <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/cheval&picture=0&lang=fr">ballade</a> a cheval a travers les differents sites de ruines. Elle n'est pas tres rassuree de partir seule et me propose de l'accompagner. Je reflechis facilement un quart de secondes avant d'accepter. 20 Soles pour 2-3h de cheval ca ne se refuse pas! ;-) Elle monte Blanca, et moi Inti, le guide nous suit a pied!<p>
Nous visitons deux sites, a chaque fois nous descendons pour prendre des photos, puis notre guide est miraculeusement remplace par un petit garcon de 8 ans, Abel (qui court aussi derriere les chevaux). La ballade est tres agreable, au milieu des arbres, loin de la route, et nous arrivons au troisieme site, qui ressemble encore plus a un tas de cailloux que les autres sites. Je commence a penser que les incas sont une tribu neolithique. Nous suivons un groupe de Peruviens qui s'amusent a passer dans les gouffres et les tunnels. Andy (qui parle francais), Alan et Edward. Karine les suit dans le tunnel, je les attends a la sortie. Apres un bon quart d'heure, ils emergent l'un apres l'autre, apres une escalade de 4 metres de haut dans le noir. Je me felicite de ma circonspection, et il se met a pleuvoir aussitot. On ne peut donc plus faire de cheval. Le temps de donner un petit pourboire (enfin, plutot pourmanger) a Abel, la pluie est battante, nous courons sur le bord de la route apres les taxis (pleins) et les autobus (pleins) qui nous ignorent. On finit par en trouver un, direction nos hotels respectifs, rendez-vous ce soir a 19h au cafe internet Mama Africa.<p>
Karine doit prendre son bus a 20h30: les adieux sont rapides, on demande a deux filles de la table d'a cote de faire une photo de groupe. Karine partie, nous voila a la table des deux belges (Audrey et Caroline) qui nous parlent de Pisaq. Tout le monde rentre, je passe au Mama Africa pour tater l'ambiance. Finalement je rentre me coucher tot.<p>
<h2>22 janvier</h2>
Je passe l'apres-midi dans les ruines de <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/pisaq&picture=0&lang=fr">Pisaq</a>. Le voyage a dure 1 heure en mini-bus dans les routes de montagne. Je prends un taxi jusqu'aux ruines, il faut encore monter a pied une pente tres raide pendant un quart d'heure. Je suis epuise. Apres, c'est facile: ca descend tout le temps. Il y a trois sites, enfin d'apres ce que j'ai vu. Le troisieme est le plus beau, je me depeche de prendre les <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/pisaq&picture=3&lang=fr">photos</a> car la pluie (traditionnelle ici en fin d'apres-midi) menace. Je suis de retour en debut de soiree au cafe internet Mama Africa, ou je retrouve les Peruviens et les Belges. Direction le Mama Africa (la boite!). Et la, je le dis tout de go: c'est beaucoup mieux en groupe. On reste danser jusque tard dans la nuit.<p>
<h2>23 janvier</h2>
Aujourd'hui, j'avais prevu d'aller au Macchu Picchu, donc j'etais cense aller a la gare (on ne peut pas y aller en bus) pour prendre mon billet pour Agua Calientes (la station de train en bas du Macchu Picchu). J'ai eu un malheureux contretemps en forme de gueule de bois. Debut d'apres-midi, la gare est fermee, je me rabats sur la formule bus jusqu'a Ollantaytambo, puis train jusqu'a Agua Calientes.
Je quitte l'hotel, et le mini-bus (5 Soles) me depose a Ollanta vers 19h. C'est un petit bourg, un peu comme Pisaq. La nuit est tombee. De la, je cherche une auberge pas cher, quartier San Isidro. J'y rencontre un jeune sympa qui fait le tour des auberges du quartier avec moi, il arrive a me negocier une chambre pour 10 Soles. Repas sur la place principale (je n'ai pas verifie le nom, mais je suis a peu pres certain que c'est la Plaza de Armas. Plusieurs tables sont sorties, et les gens (locaux et tourisates) mangent dehors. Je goute le choclo de mais. C'est un epi de mais blanc avec des grains enormes. Bon, mais bourratif. Je vais dormir comme une masse.<p>
<h2>24 janvier</h2>
Lever a 6h30 pour etre present a l'ouverture de la gare, je sais que le premier train passe tot. La, deception: le guichetier me dit que le train est complet, il ne reste qu'une place parce qu'une des passagere a decide de changer son depart au dernier moment. J'achete le billet (tarif Cuzco-Aguas Calientes de 20$ au lieu du Ollanta-Aguas Calientes a 10$ espere). De toutes facons, il est impossible de verifier ce qu'il dit.<p>
Dans le <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/macchu&picture=15&lang=fr">train</a>, je rencontre deux Argentines, qui ont decide de partir en vacances malgre la crise. Leticia et Dorita. Je travaille mon espagnol pendant une bonne partie du voyage, puis nous sommes absorbes par le spectacle. Le fleuve Urubamba qui suit la voie ferree (ou plutot l'inverse) est dechaine. C'est la saison des pluies, et il y en a eu de grosses quelques jours plus tot. On se dit au revoir, apres avoir echange les e-mails, sur le quai de la gare. Une minute plus tard, je rencontre les deux Belges (Surprise!), une minute de plus et je tombe sur Cedric et Stephanie de l'Hotel Espana a Lima (Surprise! Surprise!). Il fait un temps de merde, disons-le. Les deux Belges trouvent une auberge pour nous 5, et elles decident de visiter le Macchu Picchu le jour-meme. Avec Cedrid et Steph, on se donne un jour pour reflechir. Et nous avons reflechi, de bar en bar, le long de la route principale (tres pentue) d'Aguas Calientes. La pluie ayant un petit peu diminue, nous allons faire une petite promenade le long de la voie ferree, qui continue sur quelques kms apres la gare d'Agua Calientes. D'apres Francisco, c'est tres joli me disent-ils. Donc on est partis. On decide de marcher sur les rails, Steph n'est pas tres rassuree lorsque nous passons sous un tunnel, mais nous la rassurons car aucun train n'a l'air de passer ici depuis tres longtemps. Apres 2 kms, la pluie remet ca de plus belle, et nous decidons de rentrer. Nous nous re-installons dans un bar, nous sommes trempes. Donc, nous reflechissions de plus belle lorsque nous reconnaissons en meme temps un touriste sur le trottoir d'en face: Etienne. Cedric et Steph l'ont rencontre a l'hotel Espana un jour avant moi! Du coup, il est venu reflechir avec nous. Et Caro n'etait pas loin non plus. Ils sont alles sur le Macchu Picchu aujourd'hui tres tot, attendu sous une bache au sommet du Huayna Picchu que le temps se decouvre, mais rien a faire, ils sont rentres bredouille. Caramba!<p>
Un peu plus tard, nous allons jouer a l'arana (grenouille) dans un restaurant. C'est un jeu d'adresse ou il faut lancer des petits palets en metal dans la gueule d'une grenouille en bronze. Ca passe le temps pendant qu'on nous prepare les plats. Francisco et Kooki arrivent peu apres, ils ont fait la meme promenade que nous, mais sont alles un peu plus loin. Comme ils etaient fatigues, ils ont pris le train pour le retour. Le train ? Cedric et moi on se regarde par en dessous, il faut a tout prix eviter de croiser le regard de Steph!
Repas sympa, ca me change du bourratif-pas cher que j'ai ingurgite jusqu'ici. C'est Caro qui est contente! Les Suisses-Italiens prennent une pizza, ce qui n'etait pas une bonne idee.<p>
<h2>25 janvier</h2>
Lever 5h, Je monte le Macchu Picchu a pied avec les deux Suisses. La montee est assez raide, on arrive en haut en a peu pres 40 minutes. Le temps que les portes s'ouvrent, et on se precipite a <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/huayna&picture=0&lang=fr">l'entree du Huayna Picchu</a>, c'est une montagne juste a cote du Macchu Picchu, d'ou on peut prendre les plus belles photos. Nous ne sommes pas les premiers a tenter <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/huayna/ascension&picture=2&lang=fr">l'ascension</a>, nous sommes devances par un Americain et un Japonais. Ici, c'est une autre histoire. La pente est plus raide, par contre il est impossible d'avoir le vertige: il y a trop de brouillard. La vegetation est dense et le soleil du matin prevoque des nuages epais de condensation tout autour de nous. On voit quand meme notre route, ce n'est pas la puree de pois, heureusement! La pente est de plus en plus raide, nous sommes aides par le guide de l'Americain qui est arrive un peu plus tard que son client, du coup nous profitons des explications pour la montee. Les derniers metres sont les plus durs, on se sert des pieds et des mains pour grimper le dernier escalier. Enfin, nous arrivons en haut. De la le panorama est magnifique: du <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/huayna&picture=13&lang=fr">brouillard</a> a perte de vue. Il est environ huit heures. Nous allons attendre paisiblement que ca se degage. A 9h, <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/huayna&picture=15&lang=fr">"terre!"</a> On voit un bout du site, le silence est rompu par le "bzz-bzz" des appareils auto-focus. Peu a peu, le Macchu Picchu se degage et vers 9h30, nous prenons nos premieres photos d'ensemble. Ca valait le coup, finalement. A cette heure, il y a peu de touristes sur le site. Nous restons un peu la-haut, puis les autres touristes arrivant en masse, nous decidons de <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/huayna/descente&picture=0&lang=fr">laisser la place</a>. Nous en croisons plusieurs en route. Ils ont l'air desesperes! Et dire que nous avons ete comme ca quelques heures plus tot!<p>
Nous les encourageons comme nous pouvons:<br>
- C'est encore loin ?<br>
- Non, vous arrivez bientot a la moitie!<br>
- C'est plus facile apres ?<br>
- Pensez-vous, c'est de plus en plus dur, au contraire!<br>
Ce qu'ils ont l'air malheureux, ca fait plaisir a voir.<p>
Arrives en bas du Huayna Picchu, nous signons le registre, pres de cent personnes sont montees entretemps. Il est 11h. Nous retrouvons <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/macchu&picture=4&lang=fr">Cedric et Steph</a>, et je visite le <a href="http://www.erwan-adm.org/picture.php?album=amsud/cuzco/macchu&picture=9&lang=fr">Macchu Picchu</a> avec eux. Le soleil se montre seulement par intermittences, mais la vue est degagee. Nous entreprenons la descente tous ensemble en fin d'apres-midi. Tous rentrent par le train du soir, je decide de rester jusqu'au lendemain matin pour prendre le train "Backpacker", moins cher.<p>
Le soir, je vais prendre un bain dans les sources chaudes, c'est plein de monde. Apres ce bon bain delassant, je m'apprete a passer une soiree de fou (on est samedi soir) a A. Calientes. A part deux-trois chiens errants et quelques enfants, tout semble vide. Tout est vide. Restaurant, rencontre avec un couple de Francais. il s'appelle Fred, il travaile dans le vin et cherche un stage d'oenologue au Chili. Le veinard. Sa copine Steph l'accompagne pour les vacances. Nous allons prendre un verre dans ce qui ressemble au haut'lieu du tourisme local. Nous sommes tous les 3, plus un local qui a l'air bien emeche. C'est un artisan qui fabrique des instruments locaux, dont le "Hekkeke", une grande flute dont le son ressemble a s'y meprendre a celui d'un saxophone.<p>
<h2>26 janvier</h2>
Le train me depose a Ollamtaytambo, d'ou je prends un minibus pour Cuzco. Je depose mon sac a dos au Royal Cuzco pour la journee, le temps de prendre mon billet pour La Paz. Ensuite, je me decide a visiter la cathedrale. Sur la plaza de Armas, quelqu'un m'appelle, c'est Francisco mais j'ai du mal a le reconnaitre: il vient de raser sa barbe de 3 mois. Meconnaissable, on dirait son petit frere!<p>
La visite dure 15 minutes: je ne suis pas un grand fan d'eglises ni de cathedrales...<p>
Je le retrouve au C.I.M.A. (cafe internet Mama Africa), nous y retrouvons les Belges dont c'est apparemment devenu le quartier general. Un dernier repas entre amis dans un petit restau pas cher, et je pars pour La Paz dans un bus cama (c'est-a-dire couchette, enfin ce sont plutot des sieges inclinables avec plus de crans que la normale). Nous nous arretons a Puno (le matin) ou nous prenons un bus pourri, direction Copacabana ou nous nous arretons une heure sous la pluie. La, nous prenons un petit bus, nous traversons le lac Titicaca sur une barge et c'est reparti pour la route de montagne. Montagne-mer-montagne, heureusement que je n'ai pas trop mange a Copacabana. Nous arrivons a La Paz par l'Alto, vues superbes de fin d'apres-midi sur la ville. Arrives au centre-ville, je grimpe une longue rue avec le sac a dos, jusqu'a l'hotel Universo, qui sera mon Q.G. pour la semaine.<p>
</div>


<p>
<a href="#top">Revenir en haut</a>
</p>

 </div>
<?php
require("/home/emahe/Desktop/tdm/web/footer.html");
?> 
